### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by NuZiuki240Hz** [ParadiseFN/Moonlight#1]
Would you do a backend tutorial?

**Comment by andr1ww** [comment]
This is not finished but if you want to use it you will need to go in the src and change a few things and then just launch up your game using a ssl bypass that redirects to moonlight port which is 2912

**Comment by NuZiuki240Hz** [comment]
how do we use I don't see start.bat?

**Comment by defcharles** [comment]
you don't need a start.bat are you sped

**Comment by NuZiuki240Hz** [comment]
how do we do then ? because I don't see I can start it

**Comment by andr1ww** [comment]
You can manually start it by using npm i to install the packages and librarys needed to run moonlight then do node main/index.js and if that doesnt work then node .

**Comment by NuZiuki240Hz** [comment]
![image](https://github.com/ParadiseFN/Moonlight/assets/107798002/bfd05463-b0be-4efb-9117-ddfec7b268cb)

**Comment by andr1ww** [comment]
Just do "npm i" not npm i to install

**Comment by andr1ww** [comment]
If we help you please star this repository so we can get higher and more known!

**Comment by NuZiuki240Hz** [comment]
![image](https://github.com/ParadiseFN/Moonlight/assets/107798002/6e375d4c-217e-4e02-8aa7-458e481ff161)

**Comment by andr1ww** [comment]
I told you, that you can try both? this is very hard to help you if you arent listening.. node main/index.js

**Comment by NuZiuki240Hz** [comment]
![image](https://github.com/ParadiseFN/Moonlight/assets/107798002/61ac9e5b-7bc9-472a-9e5c-e1d47de2820a)
?

**Comment by andr1ww** [comment]
homie you just do the command my god its not that hard.

**Comment by NuZiuki240Hz** [comment]
I can't work ;/

**Comment by NuZiuki240Hz** [comment]
I figured out how to create a Fortnite account now?

**Comment by andr1ww** [comment]
you just load into the game connecting to moonlight. On moonlight you dont need to make a account it is automatically created..
